import Script from "next/script";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script src="https://www.gstatic.com/firebasejs/7.13.0/firebase-app.js" />
        <Script src="https://www.gstatic.com/firebasejs/7.13.0/firebase-messaging.js" />
      </body>
    </html>
  );
}
